### ISSUE TITLE
Move DocumentStore to own repository

### ISSUE THREAD

**Issue by sandrokeil** [proophsoftware/event-machine#103]
It would be useful to move `\Prooph\EventMachine\Persistence\DocumentStore` to an own repository called `document-store`, at least for test cases. We have three document stores at the moment:

- postgres
- mongodb if [mongodb-event-store](https://github.com/sandrokeil/mongodb-event-store) has been released
- arangodb if [arangodb-event-store](https://github.com/sandrokeil/arangodb-event-store) has been released

It shoud be possible to use any document store independent of used event store implementation, too.

**Comment by sandrokeil** [comment]
Repo for [MongoDB Document Store](https://github.com/sandrokeil/mongodb-document-store)

**Comment by sandrokeil** [comment]
@codeliner Should this be considered before release 1.0? It's not a BC break.

**Comment by codeliner** [comment]
We can do it before v1.0, but I want to move more packages to own repos after v1.0:
- JsonSchema stuff
- ImmutableRecord helpers
- ServiceFactory aka. Discolight

**Comment by martin-schilling** [comment]
I started working on a ArangoDB document store a few months ago but did not finish it. My plan is to finish it some time soon when I have the time for it. Just so you‘re aware

**Comment by codeliner** [comment]
Will be part of EE v0.2: https://github.com/event-engine/php-engine/releases
