### ISSUE TITLE
Use PHPStan before release 1.0.0

### ISSUE THREAD

**Issue by sandrokeil** [proophsoftware/event-machine#109]
Maybe some issues (Comments, Types, Checks) can be fixed before release 1.0.0 with [PHPStan](https://github.com/phpstan/phpstan). Can I bring a PR based on #108 ?

**Comment by codeliner** [comment]
sounds good

**Comment by codeliner** [comment]
but we should not focus that much on Event Machine internals for v1.0. It's just a stable release to make sure that existing projects don't break. We should focus on v2.0 without prooph/event-sourcing and prooph/service-bus.

**Comment by codeliner** [comment]
Let's focus on Event Engine and use PHPStan there: https://github.com/event-engine/php-engine/releases
