### ISSUE TITLE
HTTP endpoints should use PSR-15

### ISSUE THREAD

**Issue by codeliner** [proophsoftware/event-machine#73]
Wait until expressive 3.0 is available

**Comment by camuthig** [comment]
Should the message box implementation be moved to https://github.com/prooph/http-middleware in some way? Haven't put much thought into it yet, so this is just a high-level question.

**Comment by codeliner** [comment]
It's a special version that does some Event Machine related things. The http-middleware package contains a similar message box but without Event Machine dependencies.
