### ISSUE TITLE
Build messagebox explorer

### ISSUE THREAD

**Issue by camuthig** [proophsoftware/event-machine#77]
The messagebox provides similar functionality to GraphQL in that it allows us to send both commands and queries to a single endpoint. Unlike GraphQL and GraphiQL, we don't have a good way to document and explore the capabilities of the messagebox. If we can build something similar to GraphiQL, though, we can have the benefits of an explorable API and use the full capabilities of JSON schema instead of losing some to support GraphQL.

I believe a first step that needs to be completed for this is to support functionality from JSON schema draft 7 ([hyper schema](http://json-schema.org/draft-07/json-schema-release-notes.html)) and to include all `definitions` in the messagebox-schema. This would allow for the schema to define the response types on the query objects. 

Once the responses can be fully documented, we can build out a web interface to support parsing the schema and displaying it for the end user. Something like https://github.com/mozilla-services/react-jsonschema-form could provide a good basis for the interface.

**Comment by camuthig** [comment]
Been putting some thought, first, into what is required from the schema dumped by Event Machine. I have come up with two thoughts so far.

First, we could go hard in on the draft 7 hyper schema. The resulting schema would look something like [this](https://gist.github.com/camuthig/493ced97fbd05dca8a9cb2fc28ea181c). The schema describes a single model with an array of links, each using the base URL without modification and defining a `rel` of either "event", "command" or "query". This is an interesting proposal becaue it is able to use the offical draft. At the same time, I have found only limited support for hyper schema with regards to generating documentation/explorers, and most of those are more directed towards a standard REST application.

The other option I have been playing with is to stick with standard draft 6, which Event Machine already supports, and include a custom option for response payload of queries. The schema I have designed would look something along the lines of [this](https://gist.github.com/camuthig/6c5fffe6356d1f9bcd46e5ec54b25fe3). The schema defines properties for each "queries", "commands" and "events" that would allow us to build an explorer targeted towards each type of message. The objects under "queries" will also include a custom "response" key defining the schema of the response object. We would need to build our own support for this within a documentation/explorer generator, but that will be the case for any form of response schema.

I'm leaning towards the draft 6 option over the hyper schema option, as it keeps things a bit more simple and keeps us from needing to add draft 7 support to the project. I'm open to thoughts and opinions, though.

**Comment by codeliner** [comment]
Two very interesting options. I think the draft 6 option is my favorite, too. Also I'm not sure if draft 7 is supported by the JSON Schema lib yet, so sticking to draft 6 is good choice at the moment.
Generating the documentation/explorer should be doable. 

I try to define a roadmap next week. @camuthig Do you want to start working on it (generating the needed schema)?

**Comment by camuthig** [comment]
I'll start putting some effort into it.

**Comment by codeliner** [comment]
I think we can close this one. Swagger UI is integrated as a messagebox explorer.
