### ISSUE TITLE
ImmutableRecord VOs inside arrays are not converted

### ISSUE THREAD

**Issue by martin-schilling** [proophsoftware/event-machine#91]
When `ImmutableRecordLogic::toArray()` is called it converts the entire state to an array which in this case will be persisted using the aggregate projection. There is however a problem when the ImmutableRecord contains an array of ValueObjects because they aren't converted but instead end up in the result as objects. This will lead to the read model containing something like this `{"someData": [{},{},{}]}` which is rather unexpected. My suggestion therefore is that event-machine should either loop through the array recursively and convert all VOs to arrays or forbid this and throw an exception. The second option would force the developer to create List VOs or explicitly convert the VOs to a native type inside the state.

**Comment by codeliner** [comment]
Can you provide a failing test?

It is possible to type hint array items like shown in the [tutorial](https://proophsoftware.github.io/event-machine/tutorial/partVI.html#2-7-3)

```php
/**
     * @var array
     */
    private $users = [];

    public static function __schema(): Type
    {
        return self::generateSchemaFromPropTypeMap([
            'users' => JsonSchema::TYPE_STRING
        ]);
    }
```

ImmutableRecordLogic should throw an exception if such a hint is missing. Thought this is working already. If not we should change that.

**Comment by martin-schilling** [comment]
I will try reproducing it tomorrow and provide a suitable test. But as we already discussed, the issue is most likely due to the `__schema` method which I did not know about. If it does not work with `__schema` provided appropriately I will try to fix it. Otherwise it would probably be best to throw an exception to make it easier for others to find this kind of issue.

**Comment by codeliner** [comment]
yeah, I'm wondering why no exception is thrown

**Comment by martin-schilling** [comment]
Just tried it and I am not sure if we are talking about the same issue. Let's say I defined a class like the following
```php
final class TestProductPriceCollection implements ImmutableRecord
{
    use ImmutableRecordLogic;

    private $prices;

    public static function fromProductList(TestProductPrice ...$prices)
    {
        return self::fromRecordData([
            'prices' => $prices
        ]);
    }

    public function prices(): array
    {
        return $this->prices;
    }
}
```
and I created an instance of it like this 
```php
        $testState = TestProductPriceCollection::fromProductList(
            TestProductPrice::fromArray([
                'amount' => 3.40,
                'currency' => 'EUR'
            ])
        );
```
Now the aggregate projection would call `toArray` on it to serialize its state. although if I call it manually I end up with this 
```php
var_dump($testState->toArray());

array(1) {
  ["prices"]=>
  array(1) {
    [0]=>
    object(Prooph\EventMachineTest\Data\Stubs\TestProductPrice)#35 (2) {
      ["amount":"Prooph\EventMachineTest\Data\Stubs\TestProductPrice":private]=>
      float(3.4)
      ["currency":"Prooph\EventMachineTest\Data\Stubs\TestProductPrice":private]=>
      string(3) "EUR"
    }
  }
}
```
If you try serializing the result to JSON you will get something like this where the information was lost. 
```php
string(15) "{"prices":[{}]}"
```
I also tried overriding the `__schema` method in different ways for the `TestProductPriceCollection` which did not change the result
```php
    public static function __schema(): Type
    {
        return self::generateSchemaFromPropTypeMap([
            'prices' => JsonSchema::array(TestProductPrice::__schema())
        ]);
    }

    public static function __schema(): Type
    {
        return self::generateSchemaFromPropTypeMap([
            'prices' => TestProductPrice::__schema()
        ]);
    }
```
Am I missing something here or is my `__schema` wrong? Can it even be used to resolve this kind of problem or just to typehint something like `float[]`?

**Comment by codeliner** [comment]
Damn, seems like I've tested it only with `string[]`

In the tutorial it is used this way:

```php
        return self::generateSchemaFromPropTypeMap([
            'users' => JsonSchema::TYPE_STRING
        ]);
```

This works as expected but `ImmutableRecordLogic` does not respect the type hint when converting to array: https://github.com/proophsoftware/event-machine/blob/master/src/Data/ImmutableRecordLogic.php#L108

I'll fix that asap. Thx for reporting :+1:

**Comment by codeliner** [comment]
@martin-schilling Can you test again with latest master and this type hint:

```php
    public static function __schema(): Type
    {
        return self::generateSchemaFromPropTypeMap([
            'prices' => TestProductPrice::class
        ]);
    }
```

**Comment by martin-schilling** [comment]
Works like a charm! :+1:
